global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape the OTEL collector's own metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']

  # Scrape metrics exported by OTEL collector
  - job_name: 'ebu-metrics'
    static_configs:
      - targets: ['otel-collector:8889']
